title: SCRIPTORIUM
description: |
  Retos de `<HTML>`, `<CSS>` y `<JS>` sobre un lienzo minimalista,
  pensados para practicar, dominar y pulir tus habilidades como desarrollador web.

url: "https://mc-herrera-90.github.io"
baseurl: "/scriptorium"

# Almacenar las colecciones en un solo directorio
collections_dir: challenges
# Cada colecci√≥n es iterable usando for

collections:
  js:
    output: true
    permalink: /:collection/:name/
  html:
    output: true
    permalink: /:collection/:name/
  css:
    output: true
    permalink: /:collection/:name/

sass:
  style: compressed # compressed | expanded

# Valores por defectos para las colecciones
defaults:
  - scope:
      path: ""
      type: js
    values:
      layout: challenge
      comments: true
  - scope:
      path: ""
      type: html
    values:
      layout: challenge
      comments: true
  - scope:
      path: ""
      type: css
    values:
      layout: challenge
      comments: true
# comments:
#   provider: giscus
#   giscus:
#     repo: mc-herrera-90/scriptorium # <gh-username>/<repo>
#     repo_id: R_kgDOQ3aGVQ # <gh-repo-id>
#     category: General
#     category_id: DIC_kwDOQ3aGVc4C05O5
#     mapping: title # optional, default to 'pathname'
#     data-theme: light
#     data-lang: es
#     strict: # optional, default to '0'
#     input_position: # optional, default to 'bottom'
#     lang: es # optional, default to the value of `site.lang`
#     reactions_enabled: # optional, default to the value of `1`
