# Almacenar las colecciones en un solo directorio
collections_dir: challenges
# Cada colecci√≥n es iterable usando for
collections:
  js:
    output: true
    permalink: /:collection/:name/
  react:
    output: true
    permalink: /:collection/:name/

sass:
  style: compressed
