title: SCRIPTORIUM
description: |
  Retos de `<HTML>`, `<CSS>` y `<JS>` sobre un lienzo minimalista,
  pensados para practicar, dominar y pulir tus habilidades como desarrollador web.
# Almacenar las colecciones en un solo directorio
collections_dir: challenges
# Cada colecci√≥n es iterable usando for
collections:
  js:
    output: true
    permalink: /:collection/:name/
  html:
    output: true
    permalink: /:collection/:name/

sass:
  style: expanded # compressed | expanded

# Valores por defectos para las colecciones
defaults:
  - scope:
      path: ""
      type: js
    values:
      layout: challenge
  - scope:
      path: ""
      type: html
    values:
      layout: challenge
